# 配置自动化规则

- name: lovely_automation
  event: # detect single event.
    type: ServiceCalled # StateChanged PropertyChanged
    thing: lovaly # make system a thing too
    data:
      a: hello
      b: world
  conditions:
    - type: property # state, context
      name: brightness
      things: [lovely]
      threshold: 50
      operation: ">="

  actions:
    # TODO not only service of devices, but also logging and script etc.
    - type: service
      things: [lovely] # and system
      name: open