# 配置自动化规则

- name: lovely_automation
  if:
    event:
      - type: serviceCalled
        things: [lovely]
        data:
          a: hello
          b: world
    # check state, properties of things and context
    # sensor
  then:

