# 配置自动化规则

- name: lovely_automation
  if:
    event:
      - type: serviceCalled
        things: [lovely]
        data:
          a: hello
          b: world
    # TODO check state, properties of things and contexts of environment
    state:
      - type: property
        name: brightness
        things: [lovely]
        threshold: 50
        operation: ">="

  then:

    # TODO not only service of devices, but also logging and script etc.
    service:
      - things: [lovely]
        name: open